<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_length" value="0.1"/>
    <xacro:property name="camera_width" value="0.005"/>
    <xacro:property name="camera_height" value="0.02"/>
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
            <material name="cam_col"/>
        </visual>
        <collision>
            <geometry>
                 <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:define_box_inertia  m="0.1" x="${camera_width}" y="${camera_length}" z="${camera_height}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>
    <!-- virtual link to link our camera in order to have opencv convention -->
    <link name="camera_optical">

    </link>
   
    <joint name="base_link_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${car_length/2}  0.0 ${car_thick/2}" rpy="0.0 0.0 0.0"/>
    </joint>
    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_optical"/>
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2} 0.0 ${-pi/2}"/>
    </joint>

     <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_optical</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>            
        </sensor>
    </gazebo>

</robot>